### ISSUE TITLE
React Components load order

### ISSUE THREAD

**Issue by zachdixon** [mstamos/microreact#1]
I had a question dealing with Meteor's load order and using React Components that are loaded after they are used in the Meteor load pipeline.

For instance, in your posts components, the post_edit.jsx is using `<PostInput />` which is in post_submit.jsx... which is loaded after post_edit.jsx according to Meteor load order.

I'm currently having an issue with this, and I'm not sure what's different. Do you know anything about this?

**Comment by mstamos** [comment]
I didn't know the answer on your question @zachdixon but I read the answers on [meteor forum](https://forums.meteor.com/t/meteor-react-cjsx-file-load-order/7727) and I learned a lot. I think you found the solution you want. On my current project I use package architecture so it is more easy to set the loading order of your react components and don't care so much for global scope.

**Comment by zachdixon** [comment]
Thanks @mstamos. Yeah, loading the components in the render functions made sense, and was a decent solution. Although, I ended up going with [Universe](https://atmospherejs.com/universe/modules?__hstc=256467284.52bc63b93d6dcbead6133c40504e3459.1439617494141.1439617494141.1442183584346.2&__hssc=256467284.1.1442183584346&__hsfp=513712741) to have module support. Hoping it'll be easier to migrate to modules when Meteor implements them. This solution has worked perfectly for me so far, and is pretty close to default ES6 modules/etc so I can export/import what I need.
